[package]
name = "osci-visualizer"
version.workspace = true
edition.workspace = true

[dependencies]
osci-core = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
